data:
  dir:
    working: .
    input: ../input/icecube-neutrinos-in-deep-ice
    input_train: ${data.dir.input}/train
    input_test: ${data.dir.input}/test
    pretrained: ${data.dir.working}/pretrained
    dataset: ${data.dir.working}/dataset

  input:
    - train_meta.parquet
    - test_meta.parquet
    - sample_submission.parquet
    - sensor_geometry.csv

  ice_cube:
    pulse_table: pulse_table
    meta_table: meta_table
    train_batch: 1 # 0-650 step 10
