defaults:
  - data
  - _self_

hydra:
  run:
    dir: ../output/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: False
  job_logging:
    formatters:
      simple:
        format: "%(asctime)s [%(levelname)s][%(module)s] %(message)s"

wandb:
  enabled: True
  entity: imokuri
  project: ice-cube
  dir: ../cache
  group: ${global_params.method}

settings:
  # print_freq: 100
  # gpus: "0,1"

  debug: False
  # n_debug_data: 0

  # amp: True
  # multi_gpu: True

  in_kaggle: False
  is_training: True

  index_name: event_id
  # label_name: label
  # n_class: 1
  # scoring: pearson

params:
  seed: ${global_params.seed}

global_params:
  seed: 440
  # method: nn

preprocess_params:
  enable_h_cluster: True

cv_params:
  # n_fold: 7
  # n_validation: 1
  # fold: stratified
  # group_name: donor
  # time_name: ""

training_params:
  epoch: 20
  es_patience: 10
  batch_size: 8
  num_workers: 4
  # gradient_acc_step: 1
  # max_grad_norm: 1000
  # feature_set:
  #   - "f000" # f000_open_close
  # criterion: PearsonCCLoss # PearsonCCLoss, RMSELoss
  # optimizer: Adam
  # scheduler: CosineAnnealingWarmRestarts
  lr: 1e-3
  # min_lr: 1e-5
  eps: 1e-3
  weight_decay: 0
  # label_smoothing: 1e-6

model_params:
  target: direction
  # model: default
  # model_name: default

inference_params:
  tta: True
